require "spec_helper"
require_relative "../../app/models/event_builder"

describe EventBuilder do
  it "creates an event from an ordered list of values" do
    data = ["  2015000161923     ","TT_VERSION 1.0","CRISIS TEMPLATE","05/18/2015","NARRATIVE","05/17/2015","1234","44403","2015","161923","-","-","GO","7576","HILTON, SHAUN L","1564793","X","-","-","-","X","X","-","-","X","-","-","-","-","-","-","-","-","-","-","-","X","-","-","-","-","X","-","-","-","-","-","-","X","-","-","-","-","-","-","-","-","-","Y","N","WHITE","JENNIFER","-","-","No","-","No","-","No","-","-","-","N","-"]

    event = EventBuilder.build(data)

    expect(event.go_id).to eq("2015000161923")
    expect(event.s_version).to eq("TT_VERSION 1.0")
    expect(event.s_template).to eq("CRISIS TEMPLATE")
    expect(event.insert_time).to eq("05/18/2015")
    expect(event.trans_type).to eq("NARRATIVE")
    expect(event.reported_on_date).to eq("05/17/2015")
    expect(event.reported_on_time).to eq("1234")
    expect(event.template_id).to eq("44403")
    expect(event.report_year).to eq("2015")
    expect(event.report_number).to eq("161923")
    expect(event.version).to eq("-")
    expect(event.terry_stop_template).to eq("-")
    expect(event.event_rtype).to eq("GO")
    expect(event.reported_by).to eq("7576")
    expect(event.reported_by_trans).to eq("HILTON, SHAUN L")
    expect(event.event_rin).to eq("1564793")
    expect(event.chbk_dicv).to eq("X")
    expect(event.chbk_bodycam).to eq("-")
    expect(event.chbk_citoff_requested).to eq("-")
    expect(event.chbk_citoff_dispatched).to eq("-")
    expect(event.chbk_citoff_arrived).to eq("X")
    expect(event.chbk_biologically_induced).to eq("X")
    expect(event.chbk_medically_induced).to eq("-")
    expect(event.chbk_chemically_induced).to eq("-")
    expect(event.chbk_unknown_crisis_nature).to eq("X")
    expect(event.chbk_neglect_self_care).to eq("-")
    expect(event.chbk_disorganize_communication).to eq("-")
    expect(event.chbk_disoriented_confused).to eq("-")
    expect(event.chbk_disorderly_disruptive).to eq("-")
    expect(event.chbk_unusual_fright_scared).to eq("-")
    expect(event.chbk_belligerent_uncooperative).to eq("-")
    expect(event.chbk_hopeless_depressed).to eq("-")
    expect(event.chbk_bizarre_unusual_behavior).to eq("-")
    expect(event.chbk_suicide_threat_attempt).to eq("-")
    expect(event.chbk_mania).to eq("-")
    expect(event.chbk_out_of_touch_reality).to eq("-")
    expect(event.chbk_halluc_delusion).to eq("X")
    expect(event.chbk_behavior_other).to eq("-")
    expect(event.chbk_wpn_knife).to eq("-")
    expect(event.chbk_wpn_gun).to eq("-")
    expect(event.chbk_wpn_oth).to eq("-")
    expect(event.chbk_verbalization).to eq("X")
    expect(event.chbk_handcuffs).to eq("-")
    expect(event.chbk_reportable_force_used).to eq("-")
    expect(event.chbk_dispo_unable_to_contact).to eq("-")
    expect(event.chbk_dispo_chronic).to eq("-")
    expect(event.chbk_dispo_treatment_referral).to eq("-")
    expect(event.chbk_dispo_resource_declined).to eq("-")
    expect(event.chbk_dispo_mobile_crisis_team).to eq("X")
    expect(event.chbk_dispo_grat).to eq("-")
    expect(event.chbk_dispo_shelter).to eq("-")
    expect(event.chbk_dispo_no_action_poss_necc).to eq("-")
    expect(event.chbk_dispo_casemanager_notice).to eq("-")
    expect(event.chbk_dispo_dmhp_refer).to eq("-")
    expect(event.chbk_dispo_crisis_clinic).to eq("-")
    expect(event.chbk_dispo_emergent_ita).to eq("-")
    expect(event.chbk_dsipo_voluntary_commit).to eq("-")
    expect(event.chbk_dispo_arrested).to eq("-")
    expect(event.cit_certified_yn).to eq("Y")
    expect(event.supv_responded_scene_yn).to eq("N")
    expect(event.crisis_contacted_last_name).to eq("WHITE")
    expect(event.crisis_contacted_first_name).to eq("JENNIFER")
    expect(event.crisis_contacted_vet_yn_unk).to eq("-")
    expect(event.other_behavior_descr).to eq("-")
    expect(event.weapon_yn_dk).to eq("No")
    expect(event.other_weapon_type).to eq("-")
    expect(event.threaten_violence_yn_dk).to eq("No")
    expect(event.threatened_whom).to eq("-")
    expect(event.injuries_yn_dk).to eq("No")
    expect(event.injury_desc).to eq("-")
    expect(event.invol_hospital_transport_to).to eq("-")
    expect(event.vol_hospital_transport_to).to eq("-")
    expect(event.no_arr_but_chargeable_yn).to eq("N")
    expect(event.chbk_excited_delirium).to eq("-")
  end
end
